CEAG/CEAG.WEB/Controllers/InformacaosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CEAG.ACESSODADOS.Context;
using CEAG.DOMINIO;
using CEAG.REPOSITORIO;
using CEAG.REPOSITORIO.Genericos;
using CEAG.WEB.AutoMapper;
using CEAG.WEB.Constants;
using CEAG.WEB.ViewModel.Aluno;
using CEAG.WEB.ViewModel.Informacao;

namespace CEAG.WEB.Controllers
{
    [Authorize(Roles = "ADMINISTRADOR,DIRETOR,COORDENADOR")]
    public class InformacaosController : Controller
    {
        private IRepositorioGenerico<Aluno, int> _repositorioGenericoAluno = new RepositorioAluno(new CeagDbContext());
        private IRepositorioGenerico<Informacao, int> _repositorioGenericoInformacao = new RepositorioInformacao(new CeagDbContext());

        // GET: Informacaos
        public ActionResult Index(int codAluno)
        {
            //var config = new MapperConfiguration(cfg => cfg.CreateMap<List<Aluno>, List<AlunoExibicaoViewModel>>());
            var config = new MapperConfiguration(cfg => cfg.AddProfile<DominioParaViewModelProfile>());
            var mapper = new Mapper(config);
            List<InformacaoExibicaoViewModel> dto = mapper.Map<List<InformacaoExibicaoViewModel>>(_repositorioGenericoInformacao.Selecionar(codAluno));
            AlunoExibicaoViewModel aluno = mapper.Map<AlunoExibicaoViewModel>(_repositorioGenericoAluno.SelecionarPorId(codAluno));
            ViewBag.Aluno = aluno;
            return View(dto);
        }


        // GET: Informacaos/Create
        public ActionResult Create(int codAluno)
        {
            var config = new MapperConfiguration(cfg => cfg.AddProfile<DominioParaViewModelProfile>());
            var mapper = new Mapper(config);
            AlunoExibicaoViewModel aluno = mapper.Map<AlunoExibicaoViewModel>(_repositorioGenericoAluno.SelecionarPorId(codAluno));
            ViewBag.Aluno = aluno;

            CarregarComboTela();
            return View();
        }

        // POST: Informacaos/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(InformacaoViewModel informacaoViewModel)
        {
            var config = new MapperConfiguration(cfg => cfg.AddProfile<ViewModelParaDominioProfile>());
            var mapper = new Mapper(config);
            if (ModelState.IsValid)
            {
                var usuario = UsuarioEscola.ResgatarUsuarioLogado();

                var informacao = mapper.Map<InformacaoViewModel, Informacao>(informacaoViewModel);
                informacao.CodAcesso = usuario.CodAcesso;
                _repositorioGenericoInformacao.Inserir(informacao);

                //return RedirectToAction("Index");
                return RedirectToAction("Details", "Alunos", new { codAluno = informacao.CodAluno });
            }

            AlunoExibicaoViewModel aluno = mapper.Map<AlunoExibicaoViewModel>(_repositorioGenericoAluno.SelecionarPorId(informacaoViewModel.CodAluno));
            ViewBag.Aluno = aluno;

            CarregarComboTela();
            return View(informacaoViewModel);
        }

        // GET: Informacaos/Edit/5
        public ActionResult Edit(int? codInformacao)
        {
            if (codInformacao == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var informacao = _repositorioGenericoInformacao.SelecionarPorId(codInformacao.Value);
            var config = new MapperConfiguration(cfg => cfg.AddProfile<DominioParaViewModelProfile>());
            var mapper = new Mapper(config);

            InformacaoViewModel dto = mapper.Map<InformacaoViewModel>(informacao);
           

            if (dto == null)
            {
                return HttpNotFound();
            }
            AlunoExibicaoViewModel aluno = mapper.Map<AlunoExibicaoViewModel>(_repositorioGenericoAluno.SelecionarPorId(informacao.CodAluno));
            ViewBag.Aluno = aluno;

            CarregarComboTela();
            return View(dto);
        }

        // POST: Informacaos/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(InformacaoViewModel informacaoViewModel)
        {
            var config = new MapperConfiguration(cfg => cfg.AddProfile<ViewModelParaDominioProfile>());
            var mapper = new Mapper(config);

            if (ModelState.IsValid)
            {
                var usuario = UsuarioEscola.ResgatarUsuarioLogado();
                var informacao = mapper.Map<InformacaoViewModel, Informacao>(informacaoViewModel);
                informacao.CodAcesso = usuario.CodAcesso;
                _repositorioGenericoInformacao.Alterar(informacao);

                return RedirectToAction("Details", "Alunos", new { codAluno = informacao.CodAluno });
            }

            AlunoExibicaoViewModel aluno = mapper.Map<AlunoExibicaoViewModel>(_repositorioGenericoAluno.SelecionarPorId(informacaoViewModel.CodAluno));
            ViewBag.Aluno = aluno;

            CarregarComboTela();
            return View(informacaoViewModel);
            
        }

        // GET: Informacaos/Delete/5
        public ActionResult Delete(int? codInformacao)
        {
            if (codInformacao == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var informacaoBanco = _repositorioGenericoInformacao.SelecionarPorId(codInformacao.Value);
            if (informacaoBanco == null)
            {
                return HttpNotFound();
            }
            var config = new MapperConfiguration(cfg => cfg.AddProfile<DominioParaViewModelProfile>());
            var mapper = new Mapper(config);
            var informacaoViewModel = mapper.Map<Informacao, InformacaoViewModel>(informacaoBanco);
            AlunoExibicaoViewModel aluno = mapper.Map<AlunoExibicaoViewModel>(_repositorioGenericoAluno.SelecionarPorId(informacaoBanco.CodAluno));
            ViewBag.Aluno = aluno;

            CarregarComboTela();

            return View(informacaoViewModel);
        }

        // POST: Informacaos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int codInformacao)
        {
            var informacao = _repositorioGenericoInformacao.SelecionarPorId(codInformacao);
            _repositorioGenericoInformacao.ExcluirPorId(codInformacao);
            return RedirectToAction("Details", "Alunos", new { codAluno = informacao.CodAluno });
        }

        private void CarregarComboTela()
        {
            ViewBag.DropdownListaInformacoes = Utils.CarregarInformacoesAdicionais();
        }

      
    }
}

CEAG/CEAG.WEB/Views/Informacaos/Create.cshtml
@model  CEAG.WEB.ViewModel.Informacao.InformacaoViewModel
@{
    ViewBag.Title = "Cadastro de informação";
}
<div class="containerLopus">
    <div>
        <img src="" />
        @if (ViewBag.Aluno.Sexo.ToUpper() == "MASCULINO")
        {
            <h3><img alt="Brand" height="100" width="100" src="~/Images/Browser/todo-list.png" /> CADASTRO DE INFORMAÇÕES DO ALUNO <b>@ViewBag.Aluno.Nome</b></h3>

        }
        else
        {
            <h3><img alt="Brand" height="100" width="100" src="~/Images/Browser/todo-list.png" /> CADASTRO DE INFORMAÇÕES DA ALUNA <b>@ViewBag.Aluno.Nome</b></h3>
        }

    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.CodAluno)
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <fieldset>
                <legend>DADOS</legend>
                <div class="form-group">
                    @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.DropDownListFor(model => model.Tipo, (SelectList)ViewBag.DropdownListaInformacoes, new { @class = "form-control", data_live_search = "true", id = "ddlPacote" })
                        @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                    </div>
                </div>
            </fieldset>
            <div class="form-group">
                <div class="col-md-offset-5 col-si-offset-5 col-md-10">
                    <button type="submit">
                        <img src="~/images/Browser/ok.png" width="50" height="50"/>
                    </button>
                    <button type="button" onclick="location.href='@Url.Action("Details", "Alunos", new { codAluno = ViewBag.Aluno.CodAluno } )'">
                        <img src="~/images/Browser/cancel.png" width="50" height="50" />
                    </button>
                    @*<a href="@Url.Action("Index","Alunos")">
                            <img src="@Url.Content("~/images/Browser/cancel.png")" />
                        </a>*@
                </div>
            </div>
        </div>
    }
</div>

CEAG/CEAG.WEB/Views/Informacaos/Delete.cshtml
@model CEAG.WEB.ViewModel.Informacao.InformacaoViewModel

@{
    ViewBag.Title = "Excluir Informação";
}


<div class="containerLopus">
    <div>
        <img src="" />
        @if (ViewBag.Aluno.Sexo.ToUpper() == "MASCULINO")
        {
            <h3><img alt="Brand" height="100" width="100" src="~/Images/user-2.png" /> Deseja deletar a informação abaixo do Aluno: <b>@ViewBag.Aluno.Nome</b></h3>

        }
        else
        {
            <h3><img alt="Brand" height="100" width="100" src="~/Images/user-2.png" /> Deseja deletar a informação abaixo da Aluna: <b>@ViewBag.Aluno.Nome</b></h3>
        }

    </div>
    <hr />
    <div>
        <fieldset>
            <legend>Dados</legend>

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Tipo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Tipo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Descricao)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Descricao)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                    <div class="col-md-offset-5 col-si-offset-5 col-md-10">
                        <button type="submit" value="Delete">
                            <img src="~/images/Browser/ok.png" width="50" height="50"/>
                        </button>
                        <button type="button" onclick="location.href='@Url.Action("Details", "Alunos", new { codAluno = ViewBag.Aluno.CodAluno } )'">
                            <img src="~/images/Browser/cancel.png" width="50" height="50" />
                        </button>
                        @*<a href="@Url.Action("Index","Alunos")">
                                <img src="@Url.Content("~/images/Browser/cancel.png")" />
                            </a>*@
                    </div>
            }
        </fieldset>
    </div>
</div>

CEAG/CEAG.WEB/Views/Informacaos/Details.cshtml
@model CEAG.DOMINIO.Informacao

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Informacao</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Aluno.Matricula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aluno.Matricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CodInformacao }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CEAG/CEAG.WEB/Views/Informacaos/Edit.cshtml
@model CEAG.WEB.ViewModel.Informacao.InformacaoViewModel

@{
    ViewBag.Title = "Editar Informação";
}

<div class="containerLopus">
    <div>
        <img src="" />
        @if (ViewBag.Aluno.Sexo.ToUpper() == "MASCULINO")
        {
            <h3><img alt="Brand" height="100" width="100" src="~/Images/Browser/todo-list.png" /> ALTERAR INFORMAÇÃO DO ALUNO <b>@ViewBag.Aluno.Nome</b></h3>

        }
        else
        {
            <h3><img alt="Brand" height="100" width="100" src="~/Images/Browser/todo-list.png" /> ALTERAR INFORMAÇÃO DA ALUNA <b>@ViewBag.Aluno.Nome</b></h3>
        }

    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.CodAluno)
        @Html.HiddenFor(model => model.CodInformacao)

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <fieldset>
                <legend>DADOS</legend>
                <div class="form-group">
                    @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.DropDownListFor(model => model.Tipo, (SelectList)ViewBag.DropdownListaInformacoes, new { @class = "form-control", data_live_search = "true", id = "ddlPacote" })
                        @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                    </div>
                </div>
            </fieldset>
            <div class="form-group">
                <div class="col-md-offset-5 col-si-offset-5 col-md-10">
                    <button type="submit">
                        <img src="~/images/Browser/ok.png" width="50" height="50"/>
                    </button>
                    <button type="button" onclick="location.href='@Url.Action("Details", "Alunos", new { codAluno = ViewBag.Aluno.CodAluno } )'">
                        <img src="~/images/Browser/cancel.png" width="50" height="50"/>
                    </button>
                    @*<a href="@Url.Action("Index","Alunos")">
                            <img src="@Url.Content("~/images/Browser/cancel.png")" />
                        </a>*@
                </div>
            </div>
        </div>
    }
</div>

CEAG/CEAG.WEB/Views/Informacaos/Index.cshtml
@model IEnumerable<CEAG.WEB.ViewModel.Informacao.InformacaoExibicaoViewModel>

@{
    ViewBag.Title = "Informações";
}

<div class="containerLopus">
    <div>
        <br />
        @if (ViewBag.Aluno.Sexo.ToUpper() == "MASCULINO")
        {
            <h3><img alt="Brand" height="100" width="100" src="~/Images/user-2.png" /> Informações do Aluno: <b>@ViewBag.Aluno.Nome (Informações: @Model.Count()) </b></h3>

        }
        else
        {
            <h3><img alt="Brand" height="100" width="100" src="~/Images/user-2.png" /> Informações da Aluna: <b>@ViewBag.Aluno.Nome</b></h3>
        }

    </div>
    <hr />

    @Html.ActionLink("+ ADICIONAR INFORMAÇÃO", "Create", "Informacaos", new { codAluno = ViewBag.Aluno.CodAluno }, new { @class = "btn btn-primary but_clientes" })
    <br />
    <br />
    @foreach (var tipo in Model.Select(p => p.Tipo).Distinct())
    {
        <table class="table">
            <tr>
                <th>
                    <h3> Tipo:  <b> @tipo - @Model.Where(p => p.Tipo.Equals(tipo)).Count()</b></h3>
                </th>
                <th> <h3> <b> Ações </b></h3></th>
            </tr>

            @foreach (var item in Model.Where(p => p.Tipo.Equals(tipo)))
            {
                <tr>
                    <td width="70%">
                        <b>@Html.DisplayNameFor(model => model.Descricao):</b> @Html.DisplayFor(modelItem => item.Descricao)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit","Informacaos", new { codInformacao = item.CodInformacao})">
                            <img src="@Url.Content("~/images/ImageLink/edit-pie-chart-report.png")" width="30" height="30" title='Editar a informação do Aluno' />
                        </a>
                        @*<a href="@Url.Action("Details","Informacaos", new { id = item.CodInformacao})">
                            <img src="@Url.Content("~/images/ImageLink/view-file.png")" width="30" height="30" title='Visualizar a informação do Aluno' />
                        </a>*@
                        <a href="@Url.Action("Delete","Informacaos", new { codInformacao = item.CodInformacao})">
                            <img src="@Url.Content("~/images/ImageLink/delete.png")" width="30" height="30" title='Apagar a Informação do Aluno' />
                        </a>
                    </td>
                </tr>
            }
        </table>
        <hr class="btn-primary" />
    }
    <div class="form-group">
        <div class="col-md-offset-5 col-si-offset-5 col-md-10">
            <a href="@Url.Action("Details","Alunos", new { codAluno = @ViewBag.Aluno.CodAluno})">
                <img src="@Url.Content("~/images/Browser/cancel.png")" width="50" height="50" title='Voltar para a lista de opções' />
            </a>
        </div>
    </div>
</div>