CEAG/CEAG.WEB/Controllers/AlunosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CEAG.ACESSODADOS.Context;
using CEAG.DOMINIO;
using CEAG.NEGOCIO.Utils;
using CEAG.REPOSITORIO;
using CEAG.REPOSITORIO.Genericos;
using CEAG.WEB.AutoMapper;
using CEAG.WEB.Constants;
using CEAG.WEB.Helpers;
using CEAG.WEB.ViewModel.Aluno;
using CEAG.WEB.ViewModel.AlunoMatricula;
using CEAG.WEB.ViewModel.Debito;
using CEAG.WEB.ViewModel.Informacao;
using CEAG.WEB.ViewModel.Responsavel;
using CEAG.WEB.ViewModel.Telefone;
using CEAG.WEB.ViewModel.Turma;
using PagedList;

namespace CEAG.WEB.Controllers
{

    [Authorize(Roles = "ADMINISTRADOR,DIRETOR,COORDENADOR")]
    public class AlunosController : Controller
    {

        // GET: Alunos
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {

            #region Paginação

            ViewBag.CurrentSort = sortOrder;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            int pageSize = Constantes.PAGE_SIZE;
            int pageNumber = (page ?? 1);
            #endregion

            #region Método de consulta
            var alunos = new List<Aluno>();

            using (RepositorioAluno _repositorioAlunoLocal = new RepositorioAluno(new CeagDbContext()))
            {
                if (!string.IsNullOrEmpty(searchString))
                {
                    alunos = _repositorioAlunoLocal.Selecionar(UsuarioEscola.ResgatarCodigoEscolaSelecionada())
                    .Where(p =>
                                    p.Nome.ToUpper().Contains(searchString.ToUpper())
                                    || (p.Matricula != null && p.Matricula.ToUpper().Contains(searchString.ToUpper()))
                                    || (p.Cpf != null && p.Cpf.ToUpper().Contains(searchString.ToUpper()))
                                    || (p.MaeNome != null && p.MaeNome.ToUpper().Contains(searchString.ToUpper()))
                                    || (p.PaiNome != null && p.PaiNome.ToUpper().Contains(searchString.ToUpper()))
                                    || (p.Responsavels.Any() && p.Responsavels.Select(t => t.Nome.ToUpper()).Contains(searchString.ToUpper()))
                        //|| p.Cpf.ToUpper().Contains(pesquisa.ToUpper())

                        ).ToList();
                }
                else
                {
                    alunos = _repositorioAlunoLocal.Selecionar(UsuarioEscola.ResgatarCodigoEscolaSelecionada());
                }
            }

            #endregion

            #region Mapper

            Mapper mapper = Constants.Utils.DominioParaViewModel();

            #endregion

            //List<AlunoExibicaoViewModel> dto = mapper.Map<List<AlunoExibicaoViewModel>>(alunos);
           
            List<AlunoExibicaoViewModel> dto = new List<AlunoExibicaoViewModel>();
            foreach (var item in alunos)
            {
                AlunoExibicaoViewModel aluno = mapper.Map<AlunoExibicaoViewModel>(item);
                //aluno.ListaAlunoMatriculaExibicaoViewModel = mapper.Map<List<AlunoMatriculaExibicaoViewModel>>(item.AlunoMatriculas);
                aluno.ListaTurmasJaMatriculadas = mapper.Map<List<TurmaExibicaoViewModel>>(item.AlunoMatriculas.Select(p => p.Turma));
                dto.Add(aluno);

            }

            using (RepositorioDebito _repoLocal = new RepositorioDebito(new CeagDbContext()))
            {
                foreach (var item in dto)
                {
                    List<Debito> debitosConsulta = _repoLocal.SelecionarPorAluno(item.CodAluno);
                    item.ListaDebitosPagosAbertos = new List<DebitoExibicaoViewModel>();
                    if (debitosConsulta.Any())
                    {
                        item.ListaDebitosPagosAbertos = mapper.Map<List<DebitoExibicaoViewModel>>(debitosConsulta.OrderBy(p => p.Periodo));
                    }
                }
            }



            ViewBag.CodEscola = UsuarioEscola.ResgatarCodigoEscolaSelecionada();
            return View(dto.ToPagedList(pageNumber, pageSize));
        }

        //GET: Alunos/Details/5
        public ActionResult Details(int? codAluno)
        {

            if (codAluno == null)
            {
                return CarregarMensagemDeErro("Aluno não existe nesta escola.");
            }

            var alunoConsulta = new Aluno();

            using (RepositorioAluno _repositorioAlunoLocal = new RepositorioAluno(new CeagDbContext()))
            {
                alunoConsulta = _repositorioAlunoLocal.SelecionarPorId(codAluno.Value);
                if (alunoConsulta == null)
                {
                    return CarregarMensagemDeErro("Aluno não existe nesta escola.");
                }
            }


            if (alunoConsulta.CodEscola != UsuarioEscola.ResgatarCodigoEscolaSelecionada())
            {
                return CarregarMensagemDeErro("Aluno não existe nesta escola.");
            }

            #region Mapper

            Mapper mapper = Constants.Utils.DominioParaViewModel();

            #endregion

            AlunoExibicaoViewModel dto = mapper.Map<AlunoExibicaoViewModel>(alunoConsulta);

            Logradouro logradouroAlunoConsulta = new Logradouro();
            using (RepositorioLogradouro _repositorioGenericoLogradouroLocal = new RepositorioLogradouro(new CeagDbContext()))
            {
                logradouroAlunoConsulta = _repositorioGenericoLogradouroLocal.SelecionarPorId(dto.CodLogradouro);
            }

            if (dto == null)
            {
                return CarregarMensagemDeErro("Aluno não existe nesta escola.");
            }
            dto.Rua = logradouroAlunoConsulta.Rua;
            dto.Numero = logradouroAlunoConsulta.Numero;
            dto.Complemento = logradouroAlunoConsulta.Complemento;
            dto.Referencia = logradouroAlunoConsulta.Referencia;
            dto.Cep = logradouroAlunoConsulta.Cep;
            dto.Bairro = logradouroAlunoConsulta.Bairro;
            dto.Municipio = logradouroAlunoConsulta.Municipio;
            dto.Uf = logradouroAlunoConsulta.Uf;
            dto.CodLogradouro = logradouroAlunoConsulta.CodLogradouro;
            List<TelefoneExibicaoViewModel> telefoneAlunoConsulta = new List<TelefoneExibicaoViewModel>();
            using (RepositorioTelefone _repositorioTelefoneLocal = new RepositorioTelefone(new CeagDbContext()))
            {
                telefoneAlunoConsulta = mapper.Map<List<TelefoneExibicaoViewModel>>(_repositorioTelefoneLocal.SelecionarTelefoneAluno(dto.CodAluno));
            }

            List<Responsavel> responsavels = new List<Responsavel>();
            using (RepositorioResponsavel _repositorioGenericoResponsavelLocal = new RepositorioResponsavel(new CeagDbContext()))
            {
                responsavels = _repositorioGenericoResponsavelLocal.Selecionar(dto.CodAluno);
            }

            List<ResponsavelExibicaoViewModel> responsavelAlunoConsulta = mapper.Map<List<ResponsavelExibicaoViewModel>>(responsavels);

            List<InformacaoExibicaoViewModel> informacaoAlunoConsulta = new List<InformacaoExibicaoViewModel>();

            using (RepositorioInformacao _repositorioGenericoInformacaoLocal = new RepositorioInformacao(new CeagDbContext()))
            {
                informacaoAlunoConsulta = mapper.Map<List<InformacaoExibicaoViewModel>>(_repositorioGenericoInformacaoLocal.Selecionar(dto.CodAluno));
            }

            List<AlunoMatriculaExibicaoViewModel> alunoMatriculaExibicaoViewModels = new List<AlunoMatriculaExibicaoViewModel>();

            using (RepositorioTurma _repositorioTurmaLocal = new RepositorioTurma(new CeagDbContext()))
            {
                foreach (var item in alunoConsulta.AlunoMatriculas)
                {
                    var turmaForeach = _repositorioTurmaLocal.SelecionarPorId(item.CodTurma);
                    AlunoMatriculaExibicaoViewModel alunoMatriculaExibicaoViewModel = mapper.Map<AlunoMatriculaExibicaoViewModel>(item);
                    alunoMatriculaExibicaoViewModel.Turma = mapper.Map<TurmaExibicaoViewModel>(turmaForeach);

                    alunoMatriculaExibicaoViewModels.Add(alunoMatriculaExibicaoViewModel);
                }
            }

            List<ParentescoAluno> parentes = new List<ParentescoAluno>();
            using (RepositorioParentescoAluno _repositorioParentescoLocal = new RepositorioParentescoAluno(new CeagDbContext()))
            {
                parentes = _repositorioParentescoLocal.SelecionarParentesPorAluno(alunoConsulta.CodAluno);
            }

            List<AlunoExibicaoViewModel> alunoParenteExibicaoViewModel = new List<AlunoExibicaoViewModel>();
            using (RepositorioAluno _repoLocalAluno = new RepositorioAluno(new CeagDbContext()))
            {
                foreach (var item in parentes)
                {
                    Aluno aluno = _repoLocalAluno.SelecionarPorId(item.CodAluno.Value);
                    AlunoExibicaoViewModel alunoParente = mapper.Map<AlunoExibicaoViewModel>(aluno);
                    alunoParente.NivelParentesco = item.Parentesco.Descricao;
                    alunoParente.CodParentescoAluno = item.CodParentescoAluno;
                    foreach (var itemMatriculas in aluno.AlunoMatriculas)
                    {
                        alunoParente.ListaTurmasJaMatriculadas.Add(mapper.Map<TurmaExibicaoViewModel>(itemMatriculas.Turma));
                    }

                    //alunoParente.Matriculado = AlunoJaTemMatricula(item.CodAluno.Value).CodTurma > 0;
                    alunoParenteExibicaoViewModel.Add(alunoParente);
                }

CEAG/CEAG.WEB/Controllers/TaxasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CEAG.ACESSODADOS.Context;
using CEAG.DOMINIO;
using CEAG.NEGOCIO.Utils;
using CEAG.REPOSITORIO;
using CEAG.REPOSITORIO.Genericos;
using CEAG.WEB.AutoMapper;
using CEAG.WEB.Constants;
using CEAG.WEB.ViewModel.Taxa;
using PagedList;

namespace CEAG.WEB.Controllers
{
    [Authorize(Roles = "ADMINISTRADOR,DIRETOR,COORDENADOR")]
    public class TaxasController : Controller
    {
        private IRepositorioGenerico<Taxa, int> _repositorioGenericoTaxa = new RepositorioTaxa(new CeagDbContext());

        // GET: Taxas
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            
            #region Paginação

            ViewBag.CurrentSort = sortOrder;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            int pageSize = Constantes.PAGE_SIZE;
            int pageNumber = (page ?? 1);
            #endregion

            #region Método de consulta

            var taxas = new List<Taxa>();
            if (!string.IsNullOrEmpty(searchString))
            {
                taxas = _repositorioGenericoTaxa.Selecionar(UsuarioEscola.ResgatarCodigoEscolaSelecionada())
                .Where(p =>
                                p.Descricao.ToUpper().Contains(searchString.ToUpper())
                                || p.Tipo.ToUpper().Contains(searchString.ToUpper())
                    ).ToList();
            }
            else
            {
                taxas = _repositorioGenericoTaxa.Selecionar(UsuarioEscola.ResgatarCodigoEscolaSelecionada());
            }


            #endregion

            #region Mapper

            var config = new MapperConfiguration(cfg => cfg.AddProfile<DominioParaViewModelProfile>());
            var mapper = new Mapper(config);
            List<TaxaExibicaoViewModel> dto = mapper.Map<List<TaxaExibicaoViewModel>>(taxas);

            #endregion

            ViewBag.CodEscola = UsuarioEscola.ResgatarCodigoEscolaSelecionada();
            return View(dto.ToPagedList(pageNumber, pageSize));
        }

        // GET: Taxas/Create
        public ActionResult Create()
        {
            
            var escola = UsuarioEscola.ResgatarEscolaLogada();
            ViewBag.CodEscola = escola.CodEscola;

            CarregarComboTela();
            return View();
        }

        // POST: Taxas/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TaxaViewModel taxaViewModel)
        {
            
            taxaViewModel.Inclusao = DateTime.Now;
            taxaViewModel.CodEscola = UsuarioEscola.ResgatarCodigoEscolaSelecionada();
            if (ModelState.IsValid)
            {
                var usuario = UsuarioEscola.ResgatarUsuarioLogado();
                var config = new MapperConfiguration(cfg => cfg.AddProfile<ViewModelParaDominioProfile>());
                var mapper = new Mapper(config);

                var taxa = mapper.Map<TaxaViewModel, Taxa>(taxaViewModel);
                taxa.CodAcesso = usuario.CodAcesso;
                
                _repositorioGenericoTaxa.Inserir(taxa);
                return RedirectToAction("Index");
            }

            var escola = UsuarioEscola.ResgatarEscolaLogada();
            ViewBag.CodEscola = escola.CodEscola;

            CarregarComboTela();
            return View(taxaViewModel);
        }

        // GET: Taxas/Edit/5
        public ActionResult Edit(int? codTaxa)
        {
            
            if (codTaxa == null)
            {
                return CarregarMensagemDeErro("Taxa não existe nesta escola.");
            }

            Taxa taxaConsulta = _repositorioGenericoTaxa.SelecionarPorId(codTaxa.Value);

            if (taxaConsulta == null)
            {
                return CarregarMensagemDeErro("Taxa não existe nesta escola.");
            }

            if (taxaConsulta.CodEscola != UsuarioEscola.ResgatarCodigoEscolaSelecionada())
            {
                return CarregarMensagemDeErro("Taxa não existe nesta escola.");
            }

          

            var config = new MapperConfiguration(cfg => cfg.AddProfile<DominioParaViewModelProfile>());
            var mapper = new Mapper(config);
            TaxaViewModel dto = mapper.Map<TaxaViewModel>(taxaConsulta);

            var escola = UsuarioEscola.ResgatarEscolaLogada();
            ViewBag.Escola = escola;
            CarregarComboTela();
            return View(dto);
        }

        // POST: Taxas/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TaxaViewModel taxaViewModel)
        {
            
            taxaViewModel.Inclusao = DateTime.Now;
            taxaViewModel.CodEscola = UsuarioEscola.ResgatarCodigoEscolaSelecionada();
            if (ModelState.IsValid)
            {
                var config = new MapperConfiguration(cfg => cfg.AddProfile<ViewModelParaDominioProfile>());
                var mapper = new Mapper(config);
                var usuario = UsuarioEscola.ResgatarUsuarioLogado();
                var taxa = mapper.Map<TaxaViewModel, Taxa>(taxaViewModel);
                taxa.CodAcesso = usuario.CodAcesso;
                _repositorioGenericoTaxa.Alterar(taxa);

                return RedirectToAction("Index");
            }

            var escola = UsuarioEscola.ResgatarEscolaLogada();
            ViewBag.Escola = escola;
            return View(taxaViewModel);
        }

        
       
        public ActionResult CancelarTaxa(int codTaxa)
        {
            
            var usuario = UsuarioEscola.ResgatarUsuarioLogado();
            var taxa = _repositorioGenericoTaxa.SelecionarPorId(codTaxa);
            if (taxa.CodEscola != UsuarioEscola.ResgatarCodigoEscolaSelecionada())
            {
                return CarregarMensagemDeErro("Taxa não existe nesta escola.");
            }
            taxa.Cancelamento = DateTime.Now;
            taxa.CodAcesso = usuario.CodAcesso;
            _repositorioGenericoTaxa.Alterar(taxa);

            return RedirectToAction("Index");
        }

        private void CarregarComboTela()
        {
            ViewBag.DropdownTipoTaxa = Utils.CarregarTipoTaxas();
        }

        private ActionResult CarregarMensagemDeErro(string message)
        {
            Erro erroParametro = new Erro
            {
                CodErro = 404,
                statusCode = HttpStatusCode.BadRequest,
                MensagemErro = message,
                UrlChamada = System.Web.HttpContext.Current.Request.UrlReferrer == null ? "" : System.Web.HttpContext.Current.Request.UrlReferrer.ToString()
            };
            Session.Add("erroParametro", erroParametro);
            return RedirectToAction("ErroFinal", "Home");
        }

    }
}

CEAG/CEAG.WEB/Views/Shared/_CabecalhoEscola.cshtml
@model CEAG.DOMINIO.Escola

@{
    Layout = null;
}

<div>
    <table>
        <tr>
            <td align="center">
                <h4>
                    <b>
                        Endereço: @Model.Logradouro.Rua, @Model.Logradouro.Numero @Model.Logradouro.Bairro @Model.Logradouro.Municipio-@Model.Logradouro.Uf | CEP: @Model.Logradouro.Cep <br />
                        Autorização de funcionamento ou Decreto @Model.Autorizacao<br />
                        Publicado no D.O de @Model.PublicacaoDiarioOficial.Value.ToString("dd/MM/yyyy")<br />
                        Inscrição de cadastro Nº @Model.Inscricao
                    </b>
                </h4>
            </td>
        </tr>
    </table>
</div>

CEAG/CEAG.WEB/Views/Shared/_DebitosPagosAbertos.cshtml
@model IEnumerable<CEAG.WEB.ViewModel.Debito.DebitoExibicaoViewModel>

<table>
    <tr>
        @foreach (var item in Model)
        {
            if (@item.Pagamento.HasValue)
            {
                <td>
                    <font color="#008000">
                        <b>
                            <img src="~/Images/ImageLink/Verde.png" width="20" height="20" />
                            @item.Periodo.Month/@item.Periodo.Year
                        </b>
                    </font>
                </td>
            }
            else
            {
                <td>
                    <font color="#ff0000">
                        <b>
                            <img src="~/Images/ImageLink/Vermelho.png" width="20" height="20" />
                            @item.Periodo.Month/@item.Periodo.Year
                        </b>
                    </font>
                </td>
            }
        }
    </tr>
</table>

CEAG/CEAG.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="SHORTCUT ICON" href="~/Images/ICON.ico" />
    <title>OLIE - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>

    <div class="navbar navbar-header navbar-fixed-top navbar navbar-light" style="        background-color: #1117A3;">
        <div class="containerLopus">
            @* <img src="~/Images/download.png" />*@
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Images/ICON.ico" width="50" height="50"/>          
                <font color="#e6e9eb" class="navbar-brand"><b>OLIE </b>- GESTÃO EDUCACIONAL</font>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li id="btnInicio">
                        @*@Html.ActionLink("INICIO", "Index", "Home")*@
                        <a href="~/home/Index">
                            <b>INICIO </b>
                        </a>
                    </li>

                    <li id="btnAcademico">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <b>ACADÊMICO </b> <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            @if (User.IsInRole("ADMINISTRADOR") || User.IsInRole("COORDENADOR") || User.IsInRole("DIRETOR"))
                            {
                                <li>@Html.ActionLink("ALUNOS", "Index", "Alunos")</li>
                                <li>@Html.ActionLink("MATRICULAS", "Index", "AlunoMatriculas")</li>
                            }
                            <li>@Html.ActionLink("TURMAS", "Index", "Turmas")</li>

                            @if (User.IsInRole("ADMINISTRADOR") || User.IsInRole("COORDENADOR") || User.IsInRole("DIRETOR"))
                            {
                                <li class="nav-divider"></li>
                                <li>@Html.ActionLink("PROFESSORES", "Index", "FuncionarioDisciplinas")</li>
                                <li>@Html.ActionLink("DISCIPLINAS", "Index", "Disciplinas")</li>
                            }

                        </ul>
                    </li>
                    @if (User.IsInRole("ADMINISTRADOR") || User.IsInRole("DIRETOR"))
                    {
                        <li id="btnFinanceiro">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <b>FINANCEIRO </b><span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("VALIDAR PAGAMENTO", "ValidarQrCode", "Debitos")</li>
                                @*<li>@Html.ActionLink("NOTAS FISCAIS", "Index", ".")</li>*@
                                <li class="nav-divider"></li>
                                @*<li>@Html.ActionLink("RECEBIMENTOS", "Index", ".")</li>*@
                                <li>@Html.ActionLink("COBRANÇA", "IndexCobranca", "Debitos")</li>
                                @*<li>@Html.ActionLink("MENSALIDADES", "Index", ".")</li>*@
                                <li>@Html.ActionLink("TAXAS", "Index", "Taxas")</li>
                                <li class="nav-divider"></li>
                                <li>@Html.ActionLink("VALORES DE MENSALIDADES", "Index", "MensalidadeValors")</li>
                            </ul>
                        </li>
                    }
                    @if (User.IsInRole("ADMINISTRADOR") || User.IsInRole("COORDENADOR") || User.IsInRole("DIRETOR"))
                    {
                        <li id="btnOutros">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <b>OUTROS</b><span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("FUNCIONÁRIOS", "Index", "Funcionarios")</li>
                                <li>@Html.ActionLink("HORÁRIOS", "Index", "Horarios")</li>
                                <li>@Html.ActionLink("FERIADOS", "Index", "Feriados")</li>
                                <li>@Html.ActionLink("UNIDADES", "Index", "Unidades")</li>
                            </ul>
                        </li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @Html.ActionLink("SOBRE NÓS", "About", "Home")
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="row col-lg-12 col-md-12 col-sm-12">

        <br />
        @RenderBody()

        @*<footer class="modal-footer">
                <div class="containerLopus bg-primary">
                    <b>&copy; @DateTime.Now.Year - OLIE - GESTÃO EDUCACIONAL</b>
                    <div><b>NG SOLUTIONS</b></div>
                </div>
            </footer>*@
    </div>

    <div class="modal fade" id="modal-mensagem">
        @Html.Partial("_TelaAguarde")
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/Highcharts-4.0.1/js/highcharts.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

CEAG/CEAG.WEB/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OLIE - Gestão Educacional</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    
    <div class="row">
        <br />
        @RenderBody()
        <hr />
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CEAG/CEAG.WEB/Views/Shared/_LayoutReport.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CEAG - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
      
        @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CEAG/CEAG.WEB/Views/Shared/_TelaAguarde.cshtml
@{
    Layout = null;
}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
        </div>
        <div class="modal-body">
            <img src="~/Images/Gif/loader.gif" />
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

CEAG/CEAG.WEB/Views/Shared/_TurmasMatriculadas.cshtml
@model IEnumerable<CEAG.WEB.ViewModel.Turma.TurmaExibicaoViewModel>

<table>
    <tr>
        @foreach (var item in Model)
        {
            <td>
                [ 
                    @item.Descricao -
                    <font color="rrggbb">
                        <b>
                            @item.AnoLetivo
                        </b>
                    </font>
                ]
            </td>
        }
    </tr>
</table>