CEAG/CEAG.WEB/Controllers/AlunosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CEAG.ACESSODADOS.Context;
using CEAG.DOMINIO;
using CEAG.NEGOCIO.Utils;
using CEAG.REPOSITORIO;
using CEAG.REPOSITORIO.Genericos;
using CEAG.WEB.AutoMapper;
using CEAG.WEB.Constants;
using CEAG.WEB.Helpers;
using CEAG.WEB.ViewModel.Aluno;
using CEAG.WEB.ViewModel.AlunoMatricula;
using CEAG.WEB.ViewModel.Debito;
using CEAG.WEB.ViewModel.Informacao;
using CEAG.WEB.ViewModel.Responsavel;
using CEAG.WEB.ViewModel.Telefone;
using CEAG.WEB.ViewModel.Turma;
using PagedList;

namespace CEAG.WEB.Controllers
{

    [Authorize(Roles = "ADMINISTRADOR,DIRETOR,COORDENADOR")]
    public class AlunosController : Controller
    {

        // GET: Alunos
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {

            #region Paginação

            ViewBag.CurrentSort = sortOrder;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            int pageSize = Constantes.PAGE_SIZE;
            int pageNumber = (page ?? 1);
            #endregion

            #region Método de consulta
            var alunos = new List<Aluno>();

            using (RepositorioAluno _repositorioAlunoLocal = new RepositorioAluno(new CeagDbContext()))
            {
                if (!string.IsNullOrEmpty(searchString))
                {
                    alunos = _repositorioAlunoLocal.Selecionar(UsuarioEscola.ResgatarCodigoEscolaSelecionada())
                    .Where(p =>
                                    p.Nome.ToUpper().Contains(searchString.ToUpper())
                                    || (p.Matricula != null && p.Matricula.ToUpper().Contains(searchString.ToUpper()))
                                    || (p.Cpf != null && p.Cpf.ToUpper().Contains(searchString.ToUpper()))
                                    || (p.MaeNome != null && p.MaeNome.ToUpper().Contains(searchString.ToUpper()))
                                    || (p.PaiNome != null && p.PaiNome.ToUpper().Contains(searchString.ToUpper()))
                                    || (p.Responsavels.Any() && p.Responsavels.Select(t => t.Nome.ToUpper()).Contains(searchString.ToUpper()))
                        //|| p.Cpf.ToUpper().Contains(pesquisa.ToUpper())

                        ).ToList();
                }
                else
                {
                    alunos = _repositorioAlunoLocal.Selecionar(UsuarioEscola.ResgatarCodigoEscolaSelecionada());
                }
            }

            #endregion

            #region Mapper

            Mapper mapper = Constants.Utils.DominioParaViewModel();

            #endregion

            //List<AlunoExibicaoViewModel> dto = mapper.Map<List<AlunoExibicaoViewModel>>(alunos);
           
            List<AlunoExibicaoViewModel> dto = new List<AlunoExibicaoViewModel>();
            foreach (var item in alunos)
            {
                AlunoExibicaoViewModel aluno = mapper.Map<AlunoExibicaoViewModel>(item);
                //aluno.ListaAlunoMatriculaExibicaoViewModel = mapper.Map<List<AlunoMatriculaExibicaoViewModel>>(item.AlunoMatriculas);
                aluno.ListaTurmasJaMatriculadas = mapper.Map<List<TurmaExibicaoViewModel>>(item.AlunoMatriculas.Select(p => p.Turma));
                dto.Add(aluno);

            }

            using (RepositorioDebito _repoLocal = new RepositorioDebito(new CeagDbContext()))
            {
                foreach (var item in dto)
                {
                    List<Debito> debitosConsulta = _repoLocal.SelecionarPorAluno(item.CodAluno);
                    item.ListaDebitosPagosAbertos = new List<DebitoExibicaoViewModel>();
                    if (debitosConsulta.Any())
                    {
                        item.ListaDebitosPagosAbertos = mapper.Map<List<DebitoExibicaoViewModel>>(debitosConsulta.OrderBy(p => p.Periodo));
                    }
                }
            }



            ViewBag.CodEscola = UsuarioEscola.ResgatarCodigoEscolaSelecionada();
            return View(dto.ToPagedList(pageNumber, pageSize));
        }

        //GET: Alunos/Details/5
        public ActionResult Details(int? codAluno)
        {

            if (codAluno == null)
            {
                return CarregarMensagemDeErro("Aluno não existe nesta escola.");
            }

            var alunoConsulta = new Aluno();

            using (RepositorioAluno _repositorioAlunoLocal = new RepositorioAluno(new CeagDbContext()))
            {
                alunoConsulta = _repositorioAlunoLocal.SelecionarPorId(codAluno.Value);
                if (alunoConsulta == null)
                {
                    return CarregarMensagemDeErro("Aluno não existe nesta escola.");
                }
            }


            if (alunoConsulta.CodEscola != UsuarioEscola.ResgatarCodigoEscolaSelecionada())
            {
                return CarregarMensagemDeErro("Aluno não existe nesta escola.");
            }

            #region Mapper

            Mapper mapper = Constants.Utils.DominioParaViewModel();

            #endregion

            AlunoExibicaoViewModel dto = mapper.Map<AlunoExibicaoViewModel>(alunoConsulta);

            Logradouro logradouroAlunoConsulta = new Logradouro();
            using (RepositorioLogradouro _repositorioGenericoLogradouroLocal = new RepositorioLogradouro(new CeagDbContext()))
            {
                logradouroAlunoConsulta = _repositorioGenericoLogradouroLocal.SelecionarPorId(dto.CodLogradouro);
            }

            if (dto == null)
            {
                return CarregarMensagemDeErro("Aluno não existe nesta escola.");
            }
            dto.Rua = logradouroAlunoConsulta.Rua;
            dto.Numero = logradouroAlunoConsulta.Numero;
            dto.Complemento = logradouroAlunoConsulta.Complemento;
            dto.Referencia = logradouroAlunoConsulta.Referencia;
            dto.Cep = logradouroAlunoConsulta.Cep;
            dto.Bairro = logradouroAlunoConsulta.Bairro;
            dto.Municipio = logradouroAlunoConsulta.Municipio;
            dto.Uf = logradouroAlunoConsulta.Uf;
            dto.CodLogradouro = logradouroAlunoConsulta.CodLogradouro;
            List<TelefoneExibicaoViewModel> telefoneAlunoConsulta = new List<TelefoneExibicaoViewModel>();
            using (RepositorioTelefone _repositorioTelefoneLocal = new RepositorioTelefone(new CeagDbContext()))
            {
                telefoneAlunoConsulta = mapper.Map<List<TelefoneExibicaoViewModel>>(_repositorioTelefoneLocal.SelecionarTelefoneAluno(dto.CodAluno));
            }

            List<Responsavel> responsavels = new List<Responsavel>();
            using (RepositorioResponsavel _repositorioGenericoResponsavelLocal = new RepositorioResponsavel(new CeagDbContext()))
            {
                responsavels = _repositorioGenericoResponsavelLocal.Selecionar(dto.CodAluno);
            }

            List<ResponsavelExibicaoViewModel> responsavelAlunoConsulta = mapper.Map<List<ResponsavelExibicaoViewModel>>(responsavels);

            List<InformacaoExibicaoViewModel> informacaoAlunoConsulta = new List<InformacaoExibicaoViewModel>();

            using (RepositorioInformacao _repositorioGenericoInformacaoLocal = new RepositorioInformacao(new CeagDbContext()))
            {
                informacaoAlunoConsulta = mapper.Map<List<InformacaoExibicaoViewModel>>(_repositorioGenericoInformacaoLocal.Selecionar(dto.CodAluno));
            }

            List<AlunoMatriculaExibicaoViewModel> alunoMatriculaExibicaoViewModels = new List<AlunoMatriculaExibicaoViewModel>();

            using (RepositorioTurma _repositorioTurmaLocal = new RepositorioTurma(new CeagDbContext()))
            {
                foreach (var item in alunoConsulta.AlunoMatriculas)
                {
                    var turmaForeach = _repositorioTurmaLocal.SelecionarPorId(item.CodTurma);
                    AlunoMatriculaExibicaoViewModel alunoMatriculaExibicaoViewModel = mapper.Map<AlunoMatriculaExibicaoViewModel>(item);
                    alunoMatriculaExibicaoViewModel.Turma = mapper.Map<TurmaExibicaoViewModel>(turmaForeach);

                    alunoMatriculaExibicaoViewModels.Add(alunoMatriculaExibicaoViewModel);
                }
            }

            List<ParentescoAluno> parentes = new List<ParentescoAluno>();
            using (RepositorioParentescoAluno _repositorioParentescoLocal = new RepositorioParentescoAluno(new CeagDbContext()))
            {
                parentes = _repositorioParentescoLocal.SelecionarParentesPorAluno(alunoConsulta.CodAluno);
            }

            List<AlunoExibicaoViewModel> alunoParenteExibicaoViewModel = new List<AlunoExibicaoViewModel>();
            using (RepositorioAluno _repoLocalAluno = new RepositorioAluno(new CeagDbContext()))
            {
                foreach (var item in parentes)
                {
                    Aluno aluno = _repoLocalAluno.SelecionarPorId(item.CodAluno.Value);
                    AlunoExibicaoViewModel alunoParente = mapper.Map<AlunoExibicaoViewModel>(aluno);
                    alunoParente.NivelParentesco = item.Parentesco.Descricao;
                    alunoParente.CodParentescoAluno = item.CodParentescoAluno;
                    foreach (var itemMatriculas in aluno.AlunoMatriculas)
                    {
                        alunoParente.ListaTurmasJaMatriculadas.Add(mapper.Map<TurmaExibicaoViewModel>(itemMatriculas.Turma));
                    }

                    //alunoParente.Matriculado = AlunoJaTemMatricula(item.CodAluno.Value).CodTurma > 0;
                    alunoParenteExibicaoViewModel.Add(alunoParente);
                }

CEAG/CEAG.WEB/Controllers/FeriadosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CEAG.ACESSODADOS.Context;
using CEAG.DOMINIO;
using CEAG.NEGOCIO.Utils;
using CEAG.REPOSITORIO;
using CEAG.WEB.AutoMapper;
using CEAG.WEB.Constants;
using CEAG.WEB.ViewModel.Feriado;
using PagedList;

namespace CEAG.WEB.Controllers
{
    [Authorize(Roles = "ADMINISTRADOR,DIRETOR,COORDENADOR")]
    public class FeriadosController : Controller
    {
        private RepositorioFeriado _repositorioFeriado = new RepositorioFeriado(new CeagDbContext());

        // GET: Feriados
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            
            #region Paginação ####################

            ViewBag.CurrentSort = sortOrder;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            int pageSize = Constantes.PAGE_SIZE;
            int pageNumber = (page ?? 1);

            #endregion Paginação ####################

            #region Método de consulta ####################

            var feriados = new List<Feriado>();
            if (!string.IsNullOrEmpty(searchString))
            {
                feriados = _repositorioFeriado.Selecionar(UsuarioEscola.ResgatarCodigoEscolaSelecionada())
                .Where(p =>
                                p.Descricao.ToUpper().Contains(searchString.ToUpper())
                                || p.Tipo.ToUpper().Contains(searchString.ToUpper())
                    ).OrderByDescending(s => s.Data).ToList();
            }
            else
            {
                feriados = _repositorioFeriado.Selecionar(UsuarioEscola.ResgatarCodigoEscolaSelecionada()).OrderByDescending(s => s.Data).ToList();
            }


            #endregion Método de consulta ####################

            #region Mapper ####################

            var config = new MapperConfiguration(cfg => cfg.AddProfile<DominioParaViewModelProfile>());
            var mapper = new Mapper(config);
            List<FeriadoExibicaoViewModel> dto = mapper.Map<List<FeriadoExibicaoViewModel>>(feriados);

            #endregion Mapper ####################

            ViewBag.CodEscola = UsuarioEscola.ResgatarCodigoEscolaSelecionada();
            return View(dto.ToPagedList(pageNumber, pageSize));
        }

        // GET: Feriados/Create
        public ActionResult Create()
        {
            
            var escola = UsuarioEscola.ResgatarEscolaLogada();
            ViewBag.CodEscola = escola.CodEscola;

            CarregarComboTela();
            return View();
        }

        // POST: Feriados/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FeriadoViewModel feriadoViewModel)
        {
            
            var usuario = UsuarioEscola.ResgatarUsuarioLogado();
            feriadoViewModel.CodEscola = UsuarioEscola.ResgatarCodigoEscolaSelecionada();
            if (ModelState.IsValid)
            {
                var config = new MapperConfiguration(cfg => cfg.AddProfile<ViewModelParaDominioProfile>());
                var mapper = new Mapper(config);

                var feriado = mapper.Map<FeriadoViewModel, Feriado>(feriadoViewModel);
                feriado.CodAcesso = usuario.CodAcesso;
                _repositorioFeriado.Inserir(feriado);
                return RedirectToAction("Index");
            }

            var escola = UsuarioEscola.ResgatarEscolaLogada();
            ViewBag.CodEscola = escola.CodEscola;

            CarregarComboTela();
            return View(feriadoViewModel);
        }

        // GET: Feriados/Edit/5
        public ActionResult Edit(int? codFeriado)
        {
            
            if (codFeriado == null)
            {
                return CarregarMensagemDeErro("Feriado não existe nesta escola.");
            }

            Feriado feriadoConsulta = _repositorioFeriado.SelecionarPorId(codFeriado.Value);

            if (feriadoConsulta.CodEscola != UsuarioEscola.ResgatarCodigoEscolaSelecionada())
            {
                return CarregarMensagemDeErro("Feriado não existe nesta escola.");
            }

            if (feriadoConsulta == null)
            {
                return CarregarMensagemDeErro("Feriado não existe nesta escola.");
            }

            var config = new MapperConfiguration(cfg => cfg.AddProfile<DominioParaViewModelProfile>());
            var mapper = new Mapper(config);
            FeriadoViewModel dto = mapper.Map<FeriadoViewModel>(feriadoConsulta);

            var escola = UsuarioEscola.ResgatarEscolaLogada();
            ViewBag.Escola = escola;
            CarregarComboTela();
            return View(dto);
        }

        // POST: Feriados/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FeriadoViewModel feriadoViewModel)
        {
            
            if (ModelState.IsValid)
            {
                var usuario = UsuarioEscola.ResgatarUsuarioLogado();
                var config = new MapperConfiguration(cfg => cfg.AddProfile<ViewModelParaDominioProfile>());
                var mapper = new Mapper(config);

                var feriado = mapper.Map<FeriadoViewModel, Feriado>(feriadoViewModel);
                feriado.CodAcesso = usuario.CodAcesso;
                _repositorioFeriado.Alterar(feriado);

                return RedirectToAction("Index");
            }

            var escola = UsuarioEscola.ResgatarEscolaLogada();
            ViewBag.Escola = escola;
            return View(feriadoViewModel);
        }
        
        // POST: Feriados/Delete/5
        public ActionResult ExcluirFeriado(int codFeriado)
        {
            
            Feriado feriadoConsulta = _repositorioFeriado.SelecionarPorId(codFeriado);

            if (feriadoConsulta.CodEscola != UsuarioEscola.ResgatarCodigoEscolaSelecionada())
            {
                return CarregarMensagemDeErro("Feriado não existe nesta escola.");
            }
           
            _repositorioFeriado.ExcluirPorId(codFeriado);

            return RedirectToAction("Index");
        }

        private void CarregarComboTela()
        {
            ViewBag.DropdownTipoFeriado = Utils.CarregarTipoFeriado();
        }

        private ActionResult CarregarMensagemDeErro(string message)
        {
            Erro erroParametro = new Erro
            {
                CodErro = 404,
                statusCode = HttpStatusCode.BadRequest,
                MensagemErro = message,
                UrlChamada = System.Web.HttpContext.Current.Request.UrlReferrer == null ? "" : System.Web.HttpContext.Current.Request.UrlReferrer.ToString()
            };
            Session.Add("erroParametro", erroParametro);
            return RedirectToAction("ErroFinal", "Home");
        }
    }
}

CEAG/CEAG.WEB/Views/Feriados/Create.cshtml
@model CEAG.WEB.ViewModel.Feriado.FeriadoViewModel

@{
    ViewBag.Title = "Cadastro de Feriado";
}

<div class="containerLopus">
    <div>
        <img src="" />
        <h3><img alt="Brand" height="100" width="100" src="~/Images/Browser/crossed-out-date.png" /> INCLUSÃO DE FERIADO</h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.CodEscola)

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <fieldset>
                <legend>DADOS DO FERIADO</legend>
                <div class="form-group">
                    @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-1 col-lg-2" })
                    <div class="col-md-3 col-lg-3">
                        @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control", autocomplete = "off", @placeholder = "Digite a descrição do feriado" } })
                        @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                    </div>
                    @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-1 col-lg-1" })
                    <div class="col-md-2 col-lg-2">
                        @Html.DropDownListFor(model => model.Tipo, (SelectList)ViewBag.DropdownTipoFeriado, new { @class = "form-control", data_live_search = "true", id = "ddlTipoFeriado" })
                        @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
                    </div>
                    @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-1" })
                    <div class="col-md-2">
                        @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="form-group">
            <div class="col-md-offset-5 col-si-offset-5 col-md-10">
                <button type="submit">
                    <img src="~/images/Browser/ok.png" width="50" height="50" data-toggle="modal" data-target="#modal-mensagem" />
                </button>
                <button type="button" onclick="location.href='@Url.Action("Index", "Feriados")'">
                    <img src="~/images/Browser/cancel.png" width="50" height="50" data-toggle="modal" data-target="#modal-mensagem" />
                </button>
            </div>
        </div>

    }

</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/validations_pt-br")

}

CEAG/CEAG.WEB/Views/Feriados/Edit.cshtml
@model CEAG.WEB.ViewModel.Feriado.FeriadoViewModel

@{
    ViewBag.Title = "Cadastro de Feriado";
}

<div class="containerLopus">
    <div>
        <img src="" />
        <h3><img alt="Brand" height="100" width="100" src="~/Images/Browser/crossed-out-date.png" /> ALTERAÇÃO DE FERIADO</h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.CodEscola)
        @Html.HiddenFor(model => model.CodFeriado)
        
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <fieldset>
                <legend>DADOS DO FERIADO</legend>
                <div class="form-group">
                    @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-1 col-lg-2" })
                    <div class="col-md-3 col-lg-3">
                        @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control", autocomplete = "off", @placeholder = "Digite a descrição do feriado" } })
                        @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                    </div>
                    @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-1 col-lg-1" })
                    <div class="col-md-2 col-lg-2">
                        @Html.DropDownListFor(model => model.Tipo, (SelectList)ViewBag.DropdownTipoFeriado, new { @class = "form-control", data_live_search = "true", id = "ddlTipoFeriado" })
                        @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
                    </div>
                    @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-1" })
                    <div class="col-md-2">
                        @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="form-group">
            <div class="col-md-offset-5 col-si-offset-5 col-md-10">
                <button type="submit">
                    <img src="~/images/Browser/ok.png" width="50" height="50" data-toggle="modal" data-target="#modal-mensagem" />
                </button>
                <button type="button" onclick="location.href='@Url.Action("Index", "Feriados")'">
                    <img src="~/images/Browser/cancel.png" width="50" height="50" data-toggle="modal" data-target="#modal-mensagem" />
                </button>
            </div>
        </div>

    }

</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/validations_pt-br")

}

CEAG/CEAG.WEB/Views/Feriados/Index.cshtml
@model PagedList.IPagedList<CEAG.WEB.ViewModel.Feriado.FeriadoExibicaoViewModel>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Lista de Feriados";
}

<div class="containerLopus">
    <div>
        <img src="" />
        <h3><img alt="Brand" height="100" width="100" src="~/Images/Browser/crossed-out-date.png" /> LISTA DE FERIADOS</h3>
    </div>
    @using (Html.BeginForm("Create", "Feriados", FormMethod.Get))
    {
        <div>
            <input type="submit" id="btnAdicionar" class="btn-primary but_clientes" data-toggle="modal" data-target="#modal-mensagem" value="+ ADICIONAR FERIADO" />
        </div>
    }
    <hr />
    @using (Html.BeginForm("Index", "Feriados", FormMethod.Get))
    {
        <div class="row">
            <div class="col-md-5 col-lg-5 col-sm-5">
                @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control form-control-custom", @style = "width:90%;", @placeholder = "Digite a descrição do feriado ou o tipo" })
            </div>
            
            <div class="col-lg-3 col-sm-3 col-md-3">
                <input type="submit" id="btnPesquisar" class="btn-primary but_clientes" value="PESQUISAR" src="~/images/ImageLink/view-file.png" />
            </div>
        </div>
        <br />
    }
    <table class="table table-striped table-hover" id="tblConsulta">
        <thead class="btn-primary">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model[0].Descricao)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model[0].Tipo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model[0].Data)
                </th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td width="300">
                        @Html.DisplayFor(modelItem => item.Descricao)
                    </td>
                    <td width="200px">
                        @Html.DisplayFor(modelItem => item.Tipo)
                    </td>
                    <td width="140">
                        @Html.DisplayFor(modelItem => item.Data)
                    </td>
                    <td width="100px">
                        @*@Html.ActionLink("Alterar", "Edit", "Alunos", new { id = item.CodAluno }, new { @class = "btn btn-primary but_grid" })*@
                        <a href="@Url.Action("Edit","Feriados", new { codFeriado = item.CodFeriado})">
                            <img src="@Url.Content("~/images/ImageLink/edit-pie-chart-report.png")"data-toggle="modal" data-target="#modal-mensagem"  width="30" height="30" title='Editar o feriado' />
                        </a>
                        <a href="@Url.Action("ExcluirFeriado","Feriados", new { codFeriado = item.CodFeriado})">
                            <img src="@Url.Content("~/images/ImageLink/delete.png")" data-toggle="modal" data-target="#modal-mensagem" width="30" height="30" title='Excluir o feriado do sistema' />
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

    <hr class="btn-primary" />
    <div class="form-group">
        <div class="col-md-offset-5 col-si-offset-5 col-md-10">
            <a href="@Url.Action("Index","Home", new { codEscola = ViewBag.CodEscola})">
                <img src="@Url.Content("~/images/Browser/cancel.png")" width="50" height="50" data-toggle="modal" data-target="#modal-mensagem" title='Voltar para a lista de opções' />
            </a>
        </div>
    </div>
</div>