CEAG/CEAG.WEB/Controllers/TurmasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using AutoMapper;
using CEAG.ACESSODADOS.Context;
using CEAG.DOMINIO;
using CEAG.NEGOCIO.Utils;
using CEAG.REPOSITORIO;
using CEAG.REPOSITORIO.Genericos;
using CEAG.WEB.AutoMapper;
using CEAG.WEB.Constants;
using CEAG.WEB.ViewModel.Acesso;
using CEAG.WEB.ViewModel.Aluno;
using CEAG.WEB.ViewModel.AlunoMatricula;
using CEAG.WEB.ViewModel.Disciplina;
using CEAG.WEB.ViewModel.Funcionario;
using CEAG.WEB.ViewModel.FuncionarioDisciplina;
using CEAG.WEB.ViewModel.Horario;
using CEAG.WEB.ViewModel.Turma;
using CEAG.WEB.ViewModel.TurmaFuncionarioDisciplinas;
using PagedList;

namespace CEAG.WEB.Controllers
{
    [Authorize(Roles = "ADMINISTRADOR,DIRETOR,COORDENADOR,PROFESSOR")]
    public class TurmasController : Controller
    {
        private IRepositorioGenerico<Aluno, int> _repositorioGenericoAluno = new RepositorioAluno(new CeagDbContext());
        private RepositorioTurma _repositorioTurma = new RepositorioTurma(new CeagDbContext());
        private IRepositorioGenerico<Funcionario, int> _repositorioGenericoFuncionario = new RepositorioFuncionario(new CeagDbContext());
        private IRepositorioGenerico<Disciplina, int> _repositorioGenericoDisciplina = new RepositorioDisciplina(new CeagDbContext());
        private RepositorioTurmaFuncionarioDisciplina _repositorioTurmaFuncionarioDisciplina = new RepositorioTurmaFuncionarioDisciplina(new CeagDbContext());
        private RepositorioFuncionarioDisciplina _repositorioFuncionarioDisciplina = new RepositorioFuncionarioDisciplina(new CeagDbContext());
        private RepositorioAlunoMatricula _repositorioGenericoAlunoMatricula = new RepositorioAlunoMatricula(new CeagDbContext());
        private RepositorioHorario _repositorioHorario = new RepositorioHorario(new CeagDbContext());
        private RepositorioHorarioAula _repositorioHorarioAulas = new RepositorioHorarioAula(new CeagDbContext());

        #region Métodos de teldo padrão do scalffoding


        
        // GET: Turmas
        public ActionResult Index(string sortOrder, string currentFilter, string searchAno, string searchString, int? page)
        {
            
            #region Paginação

            ViewBag.CurrentSort = sortOrder;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            ViewBag.PesquisaAno = searchAno;

            int pageSize = Constantes.PAGE_SIZE;
            int pageNumber = (page ?? 1);
            #endregion


            AcessoViewModel usuario = UsuarioEscola.ResgatarUsuarioLogado();

            #region Método de consulta
            var turmas = new List<Turma>();
            
            if (!string.IsNullOrEmpty(searchString))
            {
                turmas = _repositorioTurma.Selecionar(UsuarioEscola.ResgatarCodigoEscolaSelecionada())
                        .Where(p =>
                                    p.Descricao.ToUpper().Contains(searchString.ToUpper())
                                    || p.Nivel.ToUpper().Contains(searchString.ToUpper())
                                    || p.Segmento.ToUpper().Contains(searchString.ToUpper())

                        ).ToList();
            }
            else
            {
                turmas = _repositorioTurma.Selecionar(UsuarioEscola.ResgatarCodigoEscolaSelecionada());
            }

            if (!string.IsNullOrEmpty(searchAno) && !searchAno.Equals("TODOS"))
            {
                turmas = turmas.Where(p => p.AnoLetivo == Convert.ToInt32(searchAno)).ToList();
            }

            if (UsuarioEscola.ResgatarUsuarioLogado().AcessoRoles[0].Role.Descricao.Equals("PROFESSOR"))
            {
                turmas = turmas.Where(p => usuario.TurmaFuncionarioDisciplinas.Select(s => s.CodTurma).Contains(p.CodTurma)).ToList();
            }


            #endregion

            #region Mapper
            Mapper mapper = Constants.Utils.DominioParaViewModel();
            #endregion

            List<TurmaExibicaoViewModel> dto = mapper.Map<List<TurmaExibicaoViewModel>>(turmas);



            ViewBag.CodEscola = UsuarioEscola.ResgatarCodigoEscolaSelecionada();
            CarregarComboTela(null);
            //return View(dto);
            return View(dto.OrderBy(p => p.Descricao).ToPagedList(pageNumber, pageSize));
        }


        [Authorize(Roles = "ADMINISTRADOR,DIRETOR,COORDENADOR")]
        // GET: Turmas/Details/5
        public ActionResult Details(int? codTurma, string sortOrder, string currentFilter, string searchString, int? page)
        {
            
            if (codTurma == null)
            {
                return CarregarMensagemDeErro("Turma não existe nesta escola.");
            }
            var turma = _repositorioTurma.SelecionarPorId(codTurma.Value);

            if (UsuarioEscola.ResgatarCodigoEscolaSelecionada() != turma.CodEscola)
            {
                return CarregarMensagemDeErro("Turma não existe nesta escola.");
            }

            #region Paginação

            ViewBag.CurrentSort = sortOrder;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            int pageSize = Constantes.PAGE_SIZE;
            int pageNumber = (page ?? 1);
            #endregion

            #region Mapper
            Mapper mapper = Constants.Utils.DominioParaViewModel();
            #endregion

            var turmaFuncionarioDisciplina = _repositorioTurmaFuncionarioDisciplina.SelecionarPorTurma(codTurma.Value);
            List<TurmaFuncionarioDisciplinaExibicaoViewModel> turmaFuncionarioDisciplinasExibicaOViewModel = new List<TurmaFuncionarioDisciplinaExibicaoViewModel>();
            foreach (var item in turmaFuncionarioDisciplina)
            {
                var foreachturmaFuncionarioDisciplina = mapper.Map<TurmaFuncionarioDisciplinaExibicaoViewModel>(item);
                var professor = mapper.Map<FuncionarioExibicaoViewModel>(item.Funcionario);
                var disciplina = mapper.Map<DisciplinaExibicaoViewModel>(item.Disciplina);
                foreachturmaFuncionarioDisciplina.Funcionario = professor;
                foreachturmaFuncionarioDisciplina.Disciplina = disciplina;
                turmaFuncionarioDisciplinasExibicaOViewModel.Add(foreachturmaFuncionarioDisciplina);
            }
            List<TurmaFuncionarioDisciplinaExibicaoViewModel> dtoTurmaFuncionarioDisciplinas = new List<TurmaFuncionarioDisciplinaExibicaoViewModel>();


            foreach (var codFuncionario in turmaFuncionarioDisciplinasExibicaOViewModel.Select(p => p.CodFuncionario).Distinct())
            {
                foreach (var professor in turmaFuncionarioDisciplinasExibicaOViewModel.Where(p => p.CodFuncionario == codFuncionario))
                {
                    foreach (var item in turmaFuncionarioDisciplinasExibicaOViewModel.Where(p => p.CodFuncionario == codFuncionario))
                    {
                        if (professor.Funcionario.Disciplinas == null)
                        {
                            professor.Funcionario.Disciplinas = item.Disciplina.Descricao;
                        }
                        else
                        {
                            if (!professor.Funcionario.Disciplinas.Contains(item.Disciplina.Descricao))
                            {
                                professor.Funcionario.Disciplinas += " | " + item.Disciplina.Descricao;
                            }
                        }

                    }

                }

                dtoTurmaFuncionarioDisciplinas.Add(turmaFuncionarioDisciplinasExibicaOViewModel.Where(p => p.CodFuncionario == codFuncionario).Take(1).SingleOrDefault());
            }

            List<AlunoMatricula> alunoMatricula = _repositorioGenericoAlunoMatricula.SelecionarPorIdTurma(codTurma.Value);

            if (!alunoMatricula.Any())
            {
                alunoMatricula.Add(new AlunoMatricula());
            }

            TurmaExibicaoViewModel dto = mapper.Map<TurmaExibicaoViewModel>(turma);

            List<AlunoMatriculaExibicaoViewModel> dtoAlunoMatricula = mapper.Map<List<AlunoMatriculaExibicaoViewModel>>(alunoMatricula);
            //List<TurmaFuncionarioDisciplinaExibicaoViewModel> dtoTurmaFuncionarioDisciplina = mapper.Map<List<TurmaFuncionarioDisciplinaExibicaoViewModel>>(turmaFuncionarioDisciplina);
            if (dtoAlunoMatricula == null)
            {
                return CarregarMensagemDeErro("Matricula não existe nesta escola.");
            }

            if (!dtoTurmaFuncionarioDisciplinas.Any())
            {
                dtoTurmaFuncionarioDisciplinas.Add(new TurmaFuncionarioDisciplinaExibicaoViewModel
                {
                    Funcionario = new FuncionarioExibicaoViewModel()
                });
            }
            dto.TurmaFuncionarioDisciplinas = dtoTurmaFuncionarioDisciplinas;

            foreach (var item in dtoAlunoMatricula)
            {
                var aluno = _repositorioGenericoAluno.SelecionarPorId(item.CodAluno);
                item.Aluno = mapper.Map<AlunoExibicaoViewModel>(aluno);
                item.Turma = dto;
            }

            
            var retorno = CarregarHorarioDaTurma(codTurma.Value);
            if (retorno == null)
            {
                return CarregarMensagemDeErro("A turma não tem horário padrão definido.");
            }

            TurmaFuncionarioDisciplinaHorarioExibicaoViewModel turmaFuncionarioDisciplinaHorarioExibicaoViewModel = retorno;// CarregarHorarioDaTurma(codTurma.Value);

CEAG/CEAG.WEB/Views/Advertencias/Create.cshtml
@model CEAG.WEB.ViewModel.Advertencia.AdvertenciaViewModel

@{
    ViewBag.Title = "Cadastro de Advertência";
}

<div class="containerLopus">
    <div>
        <img src="" />
        <h3><img alt="Brand" height="100" width="100" src="~/Images/Browser/delete-message.png" /> INCLUSÃO DE ADVERTÊNCIA PARA ALUNO</h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.CodAlunoMatricula)

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <fieldset>
                <legend>DADOS DA ADVERTÊNCIA</legend>
                <div class="form-group">
                    @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2 col-sm-2 col-lg-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                    </div>
                    @Html.LabelFor(model => model.Comparecimento, htmlAttributes: new { @class = "control-label col-md-2 col-sm-2 col-lg-2" })
                    <div class="col-md-2">
                        @Html.EditorFor(model => model.Comparecimento, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2 col-lg-2" })
                    <div class="col-md-10 col-lg-10">
                        @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control", autocomplete = "off", @placeholder = "Descreva as informações da advertência", rows = "8" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2 col-lg-2" })
                    <div class="col-md-2 col-lg-2">
                        @Html.DropDownListFor(model => model.Tipo, (SelectList)ViewBag.DropdownTipoAdvertencia, new { @class = "form-control", data_live_search = "true", id = "ddlFormaPagamento" })
                    </div>
                    @Html.LabelFor(model => model.Motivo, htmlAttributes: new { @class = "control-label col-md-1 col-sm-1 col-lg-1" })
                    <div class="col-md-3">
                        @Html.DropDownListFor(model => model.Motivo, (SelectList)ViewBag.DropdownMotivoAdvertencia, new { @class = "form-control", data_live_search = "true", id = "ddlTipoDebito" })
                    </div>
                    @Html.LabelFor(model => model.Urgencia, htmlAttributes: new { @class = "control-label col-md-1 col-sm-1 col-lg-1" })
                    <div class="col-md-3">
                        @Html.DropDownListFor(model => model.Urgencia, (SelectList)ViewBag.DropdownTipoUrgenciaAdvertencia, new { @class = "form-control", data_live_search = "true", id = "ddlTipoDebito" })
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="form-group">
            <div class="col-md-offset-5 col-si-offset-5 col-md-10">
                <button type="submit">
                    <img src="~/images/Browser/ok.png" width="50" height="50" data-toggle="modal" data-target="#modal-mensagem" />
                </button>
                <button type="button" onclick="location.href='@Url.Action("Index", "Advertencias", new { codAlunoMatricula = Model.CodAlunoMatricula})'">
                    <img src="~/images/Browser/cancel.png" width="50" height="50" data-toggle="modal" data-target="#modal-mensagem" />
                </button>
            </div>
        </div>

    }

</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/validations_pt-br")

}

CEAG/CEAG.WEB/Views/Advertencias/Delete.cshtml
@model CEAG.DOMINIO.Advertencia

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Advertencia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AlunoMatricula.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlunoMatricula.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aula.Observacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aula.Observacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Urgencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Urgencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Inclusao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Inclusao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comparecimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comparecimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CodAcesso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CodAcesso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Resolucao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Resolucao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CEAG/CEAG.WEB/Views/Advertencias/Details.cshtml
@model CEAG.DOMINIO.Advertencia

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Advertencia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AlunoMatricula.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlunoMatricula.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aula.Observacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aula.Observacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Urgencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Urgencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Inclusao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Inclusao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comparecimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comparecimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CodAcesso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CodAcesso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Resolucao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Resolucao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CodAdvertencia }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CEAG/CEAG.WEB/Views/Advertencias/Edit.cshtml
@model CEAG.WEB.ViewModel.Advertencia.AdvertenciaViewModel

@{
    ViewBag.Title = "Edição de Advertência";
}

<div class="containerLopus">
    <div>
        <img src="" />
        <h3><img alt="Brand" height="100" width="100" src="~/Images/Browser/delete-message.png" /> ALTERAR ADVERTÊNCIA</h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.CodAlunoMatricula)
        @Html.HiddenFor(model => model.CodAdvertencia)
        @Html.HiddenFor(model => model.Inclusao)
        @Html.HiddenFor(model => model.CodAula)

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <fieldset>
                <legend>DADOS DA ADVERTÊNCIA</legend>
                <div class="form-group">
                    @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2 col-sm-2 col-lg-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                    </div>
                    @Html.LabelFor(model => model.Comparecimento, htmlAttributes: new { @class = "control-label col-md-2 col-sm-2 col-lg-2" })
                    <div class="col-md-2">
                        @Html.EditorFor(model => model.Comparecimento, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2 col-lg-2" })
                    <div class="col-md-10 col-lg-10">
                        @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control", autocomplete = "off", @placeholder = "Descreva as informações da advertência", rows = "8" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2 col-lg-2" })
                    <div class="col-md-2 col-lg-2">
                        @Html.DropDownListFor(model => model.Tipo, (SelectList)ViewBag.DropdownTipoAdvertencia, new { @class = "form-control", data_live_search = "true", id = "ddlFormaPagamento" })
                    </div>
                    @Html.LabelFor(model => model.Motivo, htmlAttributes: new { @class = "control-label col-md-1 col-sm-1 col-lg-1" })
                    <div class="col-md-3">
                        @Html.DropDownListFor(model => model.Motivo, (SelectList)ViewBag.DropdownMotivoAdvertencia, new { @class = "form-control", data_live_search = "true", id = "ddlTipoDebito" })
                    </div>
                    @Html.LabelFor(model => model.Urgencia, htmlAttributes: new { @class = "control-label col-md-1 col-sm-1 col-lg-1" })
                    <div class="col-md-3">
                        @Html.DropDownListFor(model => model.Urgencia, (SelectList)ViewBag.DropdownTipoUrgenciaAdvertencia, new { @class = "form-control", data_live_search = "true", id = "ddlTipoDebito" })
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="form-group">
            <div class="col-md-offset-5 col-si-offset-5 col-md-10">
                <button type="submit">
                    <img src="~/images/Browser/ok.png" width="50" height="50" data-toggle="modal" data-target="#modal-mensagem" />
                </button>
                <button type="button" onclick="location.href='@Url.Action("Index", "Advertencias", new { codAlunoMatricula = Model.CodAlunoMatricula})'">
                    <img src="~/images/Browser/cancel.png" width="50" height="50" data-toggle="modal" data-target="#modal-mensagem" />
                </button>
            </div>
        </div>

    }

</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/validations_pt-br")

}

CEAG/CEAG.WEB/Views/Advertencias/Index.cshtml
@model IEnumerable<CEAG.WEB.ViewModel.Advertencia.AdvertenciaExibicaoViewModel>

@{
    ViewBag.Title = "Advertências do Aluno";
}
}

<div class="containerLopus">
    <div>
        <img src="" />
        <h3><img alt="Brand" height="100" width="100" src="~/Images/Browser/delete-message.png" /> LISTA DE ADVERTÊNCIAS DO ALUNO: { @Model.Count().ToString() ADVERTÊNCIAS NESTA PÁGINA }</h3> <h3 class="btn-danger"> @ViewBag.MessageError</h3>
    </div>
    @using (Html.BeginForm("Create", "Advertencias", FormMethod.Get))
    {
        <div>
            <input type="hidden" name="codAlunoMatricula" value="@ViewBag.CodAlunoMatricula" />
            <input type="submit" id="btnAdicionar" class="btn-primary but_clientes" data-toggle="modal" data-target="#modal-mensagem" value="+ ADICIONAR ADVERTÊNCIA" />
        </div>
    }
    <hr />
    <table class="table table-striped table-hover" id="tblConsulta">
        <thead class="btn-primary">
            <tr>
                <th class="cabecalho">
                    @Html.DisplayNameFor(model => model.Tipo)
                </th>
                <th class="cabecalho">
                    @Html.DisplayNameFor(model => model.Titulo)
                </th>
                <th class="cabecalho">
                    @Html.DisplayNameFor(model => model.Urgencia)
                </th>
               
                <th class="cabecalho">
                    @Html.DisplayNameFor(model => model.Motivo)
                </th>
                <th class="cabecalho">
                    @Html.DisplayNameFor(model => model.Inclusao)
                </th>
                <th class="cabecalho">
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th class="cabecalho">AÇÕES</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td width="100">
                        @Html.DisplayFor(modelItem => item.Tipo)
                    </td>
                    <td width="420" align="center">
                        @Html.DisplayFor(modelItem => item.Titulo)
                    </td>
                    <td width="100px" align="center">
                        @Html.DisplayFor(modelItem => item.Urgencia)
                    </td>
                  
                    <td width="100px" align="center">
                        @Html.DisplayFor(modelItem => item.Motivo)
                    </td>
                    <td width="100px" align="center">
                        @Html.DisplayFor(modelItem => item.Inclusao)
                    </td>
                    <td width="100px" align="center">
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>

                    <td width="160px" align="center">
                        <a href="@Url.Action("Edit","Advertencias", new { codAdvertencia = item.CodAdvertencia})">
                            <img src="@Url.Content("~/images/ImageLink/edit-pie-chart-report.png")" data-toggle="modal" data-target="#modal-mensagem" width="30" height="30" title='Negociar débito vencido' />
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <hr class="btn-primary" />
    <div class="form-group">
        <div class="col-md-offset-5 col-si-offset-5 col-md-10">
            <a href="@Url.Action("Details","Turmas", new { codTurma = ViewBag.CodTurma})">
                <img src="@Url.Content("~/images/Browser/cancel.png")" width="50" height="50" data-toggle="modal" data-target="#modal-mensagem" title='Voltar para a lista de opções' />
            </a>
        </div>
    </div>
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/validations_pt-br")
}